query MyQuery($featuredListId: uuid = "") {
  featuredList: winnibook_locals_lists(where: {id: {_eq: $featuredListId}}) {
    id
    text
    locals (where: {localByLocal: {is_active: {_eq: true}, is_confirmed: {_eq: true}}}) {
      localByLocal {
        id
        name
        main_category {
          id
          name
          theme
        }
        categories {
          category {
            id
            name
            theme
          }
        }
      }
    }
  }

  stories: winnibook_stories(where: {is_published: {_eq: true}}, limit: 4) {
    id
    title
    subtitle
    images {
      image {
        alt
        url
      }
    }
    main_category {
      id
      name
      theme
    }
  }
}
