query MyQuery {
  mostVisitedLocals: winnibook_locals(order_by: {visits: asc}, limit: 5, where: {_and: {is_active: {_eq: true}, is_confirmed: {_eq: true}}}) {
    id
    name
    main_category {
      id
      name
      theme
    }
  }
}
