query MyQuery(listId: uuid = "") {
  winnibook_locals_lists(where: {id: {_eq: listId}}) {
    id
    text
    locals (where: {localByLocal: {is_active: {_eq: true}, is_confirmed: {_eq: true}}}) {
      localByLocal {
        id
        name
        main_category {
          id
          name
          theme
        }
      }
    }
  }
}
