query localById($localId: uuid = "") {
  winnibook_locals(where: {id: {_eq: $localId}}) {
    id
    name
    description
    is_active
    is_confirmed
    categories {
      category {
        id
        name
        theme
        parent_category_id
      }
    }
    links {
      link {
        id
        name
        url
      }
    }
    main_category {
      id
      name
      theme
      parent_category_id
    }
    tags {
      tag {
        id
        name
      }
    }
    address {
      id
      latitude
      longitude
      street_line_1
      street_line_2
      postcode
      region
      city {
        id
        name
      }
    }
    contacts {
      contact {
        id
        name
        type
        value
        is_public
      }
    }
  }
}
