query localById($localId: uuid = "") {
  winnibook_locals(where: {_and: {id: {_eq: $localId}, is_active: {_eq: true}, is_confirmed: {_eq: true}}}) {
    name
    description
    id
    categories {
      category {
        id
        name
        theme
      }
    }
    links {
      link {
        id
        name
        url
      }
    }
    main_category {
      id
      name
      theme
      locals_as_main_category(limit: 2, where: {id: {_neq: $localId}, is_active: {_eq: true}, is_confirmed: {_eq: true}}) {
        id
        name
        main_category {
          id
          name
          theme
        }
        categories {
          category {
            id
            name
            theme
          }
        }
      }
    }
    stories (where: {story: {is_featured: {_eq: true}}}) {
      story {
        id
        title
        subtitle
        main_category {
          id
          name
          theme
        }
        categories {
          category {
            id
            name
            theme
          }
        }
        images {
          image {
            id
            url
            alt
          }
        }
      }
    }
    tags {
      tag {
        id
        name
      }
    }
    address {
      id
      latitude
      longitude
      street_line_1
      street_line_2
      postcode
      region
      city {
        name
      }
    }
    contacts(where: {contact: {is_public: {_eq: true}}}) {
      contact {
        id
        name
        type
        value
      }
    }
  }
}
