query MyQuery($name: String = "", $hasParent: Boolean = false) {
  winnibook_categories(where: {name: {_ilike: $name}, parent_category_id: {_is_null: $hasParent}}) {
    id
    name
    parent_category_id
    theme
  }
}
