query getAllLocals($size: Int) {
  localByName(_size: $size) {
    data {
      _id
      name
      description
      short_description
      latitude
      longitude
      streetLine1
      streetLine2
      neighbor
      city
      postcode
      contacts {
        name
        type
        value
      }
      categories {
        name
        theme
      }
      images {
        url
        alt
      }
      links {
        nameurl
      }
      tags {
        name
      }
      visits
      stories {
        title
        images {
          url
          alt
        }
      }
      employees {
        first_name
        last_name
        position
      }
    }
  }
}