query getLocalByName($name: String!) {
  localByName(name: $name) {
    data {
      _id
      name
      description
      categories {
        _id
        name #resturants
        theme
        categories #['bakeries', 'cafes']
      }
    }
  }
}