export default () => (
  <>
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Black.woff2"
      as="font"
      type="font/woff2"
      crossOrigin
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-BlackItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Bold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-BoldItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-ExtraBold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-ExtraBoldItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-ExtraLight.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-ExtraLightItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Italic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Light.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-LightItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Medium.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-MediumItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-SemiBold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-SemiBoldItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-Thin.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      rel="preload"
      href="/fonts/piazzolla/Piazzolla-ThinItalic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="true"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;700&display=swap"
      rel="stylesheet"
    ></link>
  </>
);
